### ISSUE TITLE
Move to ansible 2.x to support provision_docker in travis build

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/jboss_eap#37]
See https://www.ansible.com/blog/testing-ansible-roles-with-docker

**Comment by sherl0cks** [comment]
I've done some initial work here: https://github.com/sherl0cks/test-travis/blob/master/tests/test1.yml. Need to move that into this repo. 

@sabre1041 be advised that I hit a [weird bug with ansible 2.1](https://github.com/ansible/ansible/issues/16060). We'll need to fall back to ansible 2.0.2.0 until that is resolved.

**Comment by sabre1041** [comment]
Travis is now building with Ansible 2.4
